# Generated by Django 4.0.5 on 2022-06-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('mname', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=50)),
                ('actress', models.CharField(max_length=50)),
            ],
        ),
    ]
